/* Sheaf palette — generated by Omarchy on theme switch.
 *
 * Copy this file to ~/.config/omarchy/themed/sheaf.css.tpl
 * Omarchy then writes ~/.config/omarchy/themed/sheaf.css from it.
 * Sheaf reads that generated file first; if it is missing it falls
 * back to the active theme colors.toml, then to Adwaita.
 */

:root {
  --sheaf-bg: {{ background }};
  --sheaf-fg: {{ foreground }};
  --sheaf-accent: {{ accent }};
  --sheaf-red: {{ red }};
  --sheaf-color0: {{ color0 }};
  --sheaf-color1: {{ color1 }};
  --sheaf-color2: {{ color2 }};
  --sheaf-color3: {{ color3 }};
  --sheaf-color4: {{ color4 }};
  --sheaf-color5: {{ color5 }};
  --sheaf-color6: {{ color6 }};
  --sheaf-color7: {{ color7 }};
  --sheaf-color8: {{ color8 }};
  --sheaf-color9: {{ color9 }};
  --sheaf-color10: {{ color10 }};
  --sheaf-color11: {{ color11 }};
  --sheaf-color12: {{ color12 }};
  --sheaf-color13: {{ color13 }};
  --sheaf-color14: {{ color14 }};
  --sheaf-color15: {{ color15 }};
}

background={{ background }}
foreground={{ foreground }}
accent={{ accent }}
red={{ red }}
color0={{ color0 }}
color1={{ color1 }}
color2={{ color2 }}
color3={{ color3 }}
color4={{ color4 }}
color5={{ color5 }}
color6={{ color6 }}
color7={{ color7 }}
color8={{ color8 }}
color9={{ color9 }}
color10={{ color10 }}
color11={{ color11 }}
color12={{ color12 }}
color13={{ color13 }}
color14={{ color14 }}
color15={{ color15 }}
